import generalReducer, {
  generalSelector,
  generalSlice,
  GeneralState,
  getAcademicLevel,
  getBloodType,
  getCargos,
  getCivilState,
  getCountries,
  getDepartments,
  getEmailsTypes,
  getInfoEmpresa,
  getParametros,
  getPaymentType,
  getPayroll,
  getPersonData,
  getPhoneTypes,
  getProvinces,
  getRelationShip,
  getTypeAbsences,
  getTypesPermissions,
  getWorkingDay,
  resetAction,
} from './general'

import {
  AcademicLevelType,
  BloodType,
  CargosType,
  CivilStateType,
  CountriesType,
  DepartmentsType,
  ElationShipType,
  InfoEmpresaType,
  PaymentType,
  PayrollType,
  PersonDataType,
  ProvincesType,
  RelationshipType,
  TypesPermissions,
  WorkingDayType,
} from './types'

export const {
  setDeleteNullValuesBeforeRequest,
  setModalVisibilityStateForEmployeeSummary,
  setModalStateFormVacancy,
  setEditingMode,
  setNextLocation,
  setStepPosition,
  setStepPositionReset,
} = generalSlice.actions

export {
  getAcademicLevel,
  getBloodType,
  getCargos,
  getCivilState,
  getCountries,
  getDepartments,
  getEmailsTypes,
  getInfoEmpresa,
  getParametros,
  getPaymentType,
  getPayroll,
  getPersonData,
  getPhoneTypes,
  getProvinces,
  getRelationShip,
  getTypeAbsences,
  getTypesPermissions,
  getWorkingDay,
  resetAction,
  generalSelector,
}

export type {
  PersonDataType,
  BloodType,
  AcademicLevelType,
  TypesPermissions,
  CivilStateType,
  CountriesType,
  DepartmentsType,
  PaymentType,
  CargosType,
  PayrollType,
  WorkingDayType,
  ElationShipType,
  ProvincesType,
  InfoEmpresaType,
  RelationshipType,
  GeneralState,
}

export default generalReducer
