import { employeeSlicer } from './employee'
export {
  createAbsences,
  createAcademic,
  createAddress,
  createContactEmergency,
  createDelay,
  createDiscounts,
  createDocuments,
  createEmail,
  // createHolidays,
  createPermissions,
  createPhone,
  employeeSelector,
  employeeSlicer,
  getAbsences,
  getAcademic,
  getAddress,
  getContactEmergency,
  getDataEmployee,
  getDelay,
  getDiscounts,
  getDiscountsDescription,
  getDocTypes,
  getDocuments,
  getEmail,
  getPacientes,
  getEmployeeHistoryChange,
  getEmployeeSummary,
  getHolidays,
  getPermissions,
  getPhone,
  getValidateId,
  updateAbsences,
  updateAcademic,
  updateAddress,
  updateContactEmergency,
  updateDelay,
  updateDiscounts,
  updateDocuments,
  updateEmail,
  updateEmployee,
  updateEmploymentData,
  updateHolidays,
  updatePermissions,
  updatePhone,
  updateStateEmployee,
} from './employee'

export const {
  setEmployee,
  setAcademic,
  setContactEmergency,
  setPhone,
  setEmail,
  setDelay,
  setAbsences,
  setHolidays,
  setPermissions,
  setDiscounts,
  setDiscountsDescription,
  setRequestStatus,
  setEmployeeSummary,
  setSummary,
  setDetNominas,
  resetEmployeeState,
  setResetRegisterEmployee,
} = employeeSlicer.actions

export type { EmployeeState } from './employee'
export type {
  AbsencesType,
  AcademicType,
  AddressType,
  DataEmployeeType,
  DelayType,
  DiscountsDescriptionType,
  DiscountsType,
  DocTypesType,
  DocumentsType,
  EmailType,
  EmergencyContactType,
  EmployeeHistoryType,
  EmployeeSummaryType,
  EmployeeType,
  EmploymentDataType,
  HolidaysType,
  PermissionsType,
  PhoneType,
  UpdateStateEmployeeType,
  ValidateIdType,
  ChargesType,
  ConfigPayload,
} from './types'
export { default } from './employee'
